export enum Role {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  GERENCIA = 'GERENCIA',
  TALENTO_HUMANO = 'TALENTO_HUMANO',
  LIDER_OPERATIVO = 'LIDER_OPERATIVO',
  COORDINADOR = 'COORDINADOR',
  SUPERVISOR = 'SUPERVISOR',
}
